// Generated by CoffeeScript 2.5.1
(function() {
  var Modules;

  Modules = {
    cliargumentsmodule: require("./cliargumentsmodule"),
    debugmodule: require("./debugmodule"),
    genconfigprocessmodule: require("./genconfigprocessmodule"),
    nginxconfigmodule: require("./nginxconfigmodule"),
    startupmodule: require("./startupmodule"),
    pathhandlermodule: require("./pathhandlermodule")
  };

  module.exports = Modules;

}).call(this);
